@url = https://pokeapi.co/api/v2/

GET {{url}}/ability?limit=327 HTTP/1.1

###

GET {{url}}/pokemon?limit=1154 HTTP/1.1

###

GET {{url}}/move?limit=844 HTTP/1.1

###

GET {{url}}/pokemon/eevee/ HTTP/1.1